language: php

php:
  - '5.6'
  - '7.0'
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
   - composer install

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist
